# Generated by Django 4.0.6 on 2022-07-17 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countries',
            new_name='Countrie',
        ),
    ]
